# Generated by Django 5.1 on 2024-08-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_kagel_crop_crop_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kagel_crop',
            name='crop_label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
