# Generated by Django 5.1 on 2024-08-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_kagel_crop_crop_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kagel_crop',
            name='crop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
