# Generated by Django 5.1 on 2024-08-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_kagel_crop_crop_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['crop_level']},
        ),
        migrations.AlterModelOptions(
            name='kagel_crop',
            options={'ordering': ['crop_name']},
        ),
    ]
